---
version: "3.8"

services:
  bot-girl:
    image: konstantinpopov/enthusiast-girl:0.0.48
    ports:
      - "9002:9002"
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - TELEGRAM_APITOKEN=<secret>
      - SDLC_USER=<secret>
      - SDLC_PASSWORD=<secret>
      - QUAY_USER=<secret>
      - QUAY_PASSWORD=<secret>
      - ALERT_CHAT_ID=461794724
      - ALERT_HOOK_PORT=9002
      - GIT_HOST=<secret>

