telegram:
  token: "<secret>"
  maintainers:
    - kopopov
    - fsafsd

sdlc:
  user: "<secret>"
  password: "<secret>"

registry:
  host: "<host>"
  user: "<secret>"
  password: "<secret>"

git:
  host: "<secret>"
  user: k.popov
  email: k.popov@it.ecommpay.com

alert:
  hookPort: 461794724
  chatId: 123